# -*- coding: utf-8 -*-
"""Bản sao của Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8oFTbPtnUh0AhNo72ZrKxWwPjnmd8GT
"""

import json
import torch
from torch.utils.data import Dataset, DataLoader
import pickle

class LoadsDataset(Dataset):
    def __init__(self, json_file, column_name):
        """
        Custom Dataset to read a specific column from a JSON file.

        Args:
            json_file (str): Path to the JSON file.
            column_name (str): Name of the column to read.
        """
        with open(json_file, 'r', encoding='utf-8') as f:
            self.data = json.load(f)  # Load all JSON data.
        if column_name not in self.data[0]:
            raise ValueError(f"Column '{column_name}' does not exist in the JSON file.")

        self.column_data = [item[column_name] for item in self.data]

    def __len__(self):
        """Return the number of samples in the dataset."""
        return len(self.column_data)

    def __getitem__(self, idx):
        """
        Return a sample at index `idx`.

        Args:
            idx (int): Index of the sample to retrieve.

        Returns:
            torch.Tensor or string: The column data as a tensor or string.
        """
        sample = self.column_data[idx]
        return torch.tensor(sample, dtype=torch.float32) if isinstance(sample, (int, float)) else sample


class BatchProcessor:
    def __init__(self, json_file, column_name, batch_size=4, shuffle=False):
        """
        Batch processor to handle loading, batching, and saving data.

        Args:
            json_file (str): Path to the JSON file.
            column_name (str): Name of the column to read.
            batch_size (int): Size of each batch. Default is 4.
            shuffle (bool): Whether to shuffle the data. Default is False.
            save_path (str): Path to save the processed batches. Default is 'data.pkl'.
        """
        self.json_file = json_file
        self.column_name = column_name
        self.batch_size = batch_size
        self.shuffle = shuffle

    def load_dataset(self):
        print(f"Loading dataset from '{self.json_file}'...")
        self.dataset = JSONColumnDataset(json_file=self.json_file, column_name=self.column_name)
        print(f"Loaded dataset with {len(self.dataset)} samples.")

    def create_dataloader(self):
        print("Creating DataLoader...")
        self.dataloader = DataLoader(self.dataset, batch_size=self.batch_size, shuffle=self.shuffle)

    def process_batches(self):
        print("Processing batches...")
        self.all_batches = []

        for batch_idx, batch_data in enumerate(self.dataloader):
            self.all_batches.append(batch_data)
        print("Completetion.")


    def loads(self):
        """Run the full process: load dataset, process batches, and save them."""
        self.load_dataset()
        self.create_dataloader()
        self.process_batches()

